import { Language, User, Subject, Student } from './types';

export const TRANSLATIONS = {
  en: {
    login: "Login",
    username: "Username",
    password: "Password",
    dashboard: "Dashboard",
    students: "Students",
    teachers: "Teachers",
    subjects: "Classes",
    attendance: "Attendance",
    payments: "Payments",
    reports: "History & Reports",
    logout: "Logout",
    welcome: "Welcome",
    addStudent: "Add Student",
    addTeacher: "Add Teacher",
    name: "Name",
    phone: "Phone",
    parentPhone: "Parent Phone",
    save: "Save",
    cancel: "Cancel",
    addSubject: "Add Class",
    price: "Price",
    teacher: "Teacher",
    markAttendance: "Mark Attendance",
    present: "Present",
    absent: "Absent",
    remaining: "Sessions Left",
    validUntil: "Valid Until",
    expired: "Expired",
    pay: "Register Payment",
    amount: "Amount",
    confirmPayment: "Confirm Payment (Cash)",
    noData: "No data available",
    notifications: "Notifications",
    subscriptionWarning: "Subscription ends in 3 days",
    delete: "Delete",
    passwordPlaceholder: "Set a password",
    selectSubject: "Select Class",
    month: "Month",
    year: "Year",
    totalSessions: "Total Sessions",
    stats: "Statistics",
    class: "Class",
    search: "Search...",
  },
  ar: {
    login: "تسجيل الدخول",
    username: "اسم المستخدم",
    password: "كلمة المرور",
    dashboard: "الرئيسية",
    students: "الطلاب",
    teachers: "المعلمين",
    subjects: "الفصول",
    attendance: "الحضور",
    payments: "المدفوعات",
    reports: "السجل والتقارير",
    logout: "خروج",
    welcome: "مرحباً",
    addStudent: "إضافة طالب",
    addTeacher: "إضافة معلم",
    name: "الاسم",
    phone: "الهاتف",
    parentPhone: "هاتف الولي",
    save: "حفظ",
    cancel: "إلغاء",
    addSubject: "إضافة فصل",
    price: "السعر",
    teacher: "الأستاذ",
    markAttendance: "تسجيل الحضور",
    present: "حاضر",
    absent: "غائب",
    remaining: "حصص متبقية",
    validUntil: "صالح حتى",
    expired: "منتهية",
    pay: "تسجيل دفع",
    amount: "المبلغ",
    confirmPayment: "تأكيد الدفع",
    noData: "لا توجد بيانات",
    notifications: "الإشعارات",
    subscriptionWarning: "الاشتراك ينتهي قريباً",
    delete: "حذف",
    passwordPlaceholder: "تعيين كلمة مرور",
    selectSubject: "اختر الفصل",
    month: "الشهر",
    year: "السنة",
    totalSessions: "مجموع الحصص",
    stats: "الإحصائيات",
    class: "الفصل",
    search: "بحث...",
  },
  fr: {
    login: "Connexion",
    username: "Nom d'utilisateur",
    password: "Mot de passe",
    dashboard: "Tableau de bord",
    students: "Étudiants",
    teachers: "Enseignants",
    subjects: "Classes",
    attendance: "Présence",
    payments: "Paiements",
    reports: "Historique",
    logout: "Déconnexion",
    welcome: "Bienvenue",
    addStudent: "Ajouter étudiant",
    addTeacher: "Ajouter enseignant",
    name: "Nom",
    phone: "Téléphone",
    parentPhone: "Tél. Parent",
    save: "Enregistrer",
    cancel: "Annuler",
    addSubject: "Ajouter classe",
    price: "Prix",
    teacher: "Enseignant",
    markAttendance: "Marquer présence",
    present: "Présent",
    absent: "Absent",
    remaining: "Séances restantes",
    validUntil: "Valable jusqu'au",
    expired: "Expiré",
    pay: "Paiement",
    amount: "Montant",
    confirmPayment: "Confirmer",
    noData: "Aucune donnée",
    notifications: "Notifications",
    subscriptionWarning: "L'abonnement expire bientôt",
    delete: "Supprimer",
    passwordPlaceholder: "Mot de passe",
    selectSubject: "Choisir classe",
    month: "Mois",
    year: "Année",
    totalSessions: "Total Séances",
    stats: "Statistiques",
    class: "Classe",
    search: "Chercher...",
  }
};

// Initial Mock Data
export const INITIAL_SUBJECTS: Subject[] = [
  { id: 's1', name: 'Mathematics 101', teacherName: 'Mr. Ahmed', price: 50 },
  { id: 's2', name: 'Physics A', teacherName: 'Ms. Sarah', price: 60 },
];

// Simplified Users for easier Login
export const INITIAL_USERS: User[] = [
  { uid: 'admin1', email: 'admin', name: 'Principal', role: 'admin', password: 'admin' },
  { uid: 'teach1', email: 'teacher', name: 'Mr. Ahmed', role: 'teacher', subjectId: 's1', password: '123' },
];

export const INITIAL_STUDENTS: Student[] = [
  { 
    id: 'st1', name: 'Omar Ali', phone: '123456', parentPhone: '654321', 
    subscriptions: [
      { subjectId: 's1', sessionsRemaining: 8, validUntil: new Date(Date.now() + 86400000 * 30).toISOString() } 
    ] 
  }
];